### ISSUE TITLE
Raw file specifications

### ISSUE THREAD

**Issue by ws-garcia** [Samson-Mano/2DTriangle_Mesh_Generator#2]
This library is promising for structural analysis. It can be very useful if the specifications for raw data files are disclosed in a detailed way, so that the users can create valid entries, perhaps for testing, without the need to use external modules.

**Comment by Samson-Mano** [comment]
Thanks for your feedback. Added the specifications for raw data file.

[How_to_create_geometry_raw_surface_data.pdf](https://github.com/Samson-Mano/2DTriangle_Mesh_Generator/blob/master/How_to_create_geometry_raw_surface_data.pdf)
